# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-26 23:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllShoppingFromTaleqaniToFatemi',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('long', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('type', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
                ('first_category', models.BigIntegerField(blank=True, null=True)),
                ('second_category', models.IntegerField(blank=True, null=True)),
                ('third_category', models.IntegerField(blank=True, null=True)),
                ('product_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_shopping_from_taleqani_to__fatemi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NumericUserSearch',
            fields=[
                ('user_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('user_search_id', models.IntegerField()),
                ('numeric_first_category', models.IntegerField(blank=True, db_index=True, null=True)),
                ('numeric_second_category', models.IntegerField(blank=True, null=True)),
                ('numeric_third_category', models.IntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'numeric_user_search',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('first_category', models.IntegerField(blank=True, db_index=True, null=True)),
                ('second_category', models.IntegerField(blank=True, null=True)),
                ('third_category', models.IntegerField(blank=True, null=True)),
                ('product_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'store_products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Profession', models.CharField(default='', max_length=20)),
                ('Email', models.EmailField(max_length=200, unique=True)),
                ('Salary', models.DecimalField(decimal_places=4, max_digits=9)),
                ('User_longtitude_Coordinates', models.TextField(blank=True)),
                ('User_latitude_Coordinates', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, default='')),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
