# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='User_latitude_Coordinates',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='User_longtitude_Coordinates',
            field=models.DecimalField(decimal_places=6, max_digits=7),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
