# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-03 22:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_cost_geo', models.DecimalField(blank=True, decimal_places=4, max_digits=9)),
                ('Search_cost_sim', models.DecimalField(blank=True, decimal_places=4, max_digits=9)),
                ('Best_decision_geo', models.DecimalField(blank=True, decimal_places=4, max_digits=9)),
                ('Best_decision_sim', models.DecimalField(blank=True, decimal_places=4, max_digits=9)),
                ('Accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='poll',
            name='name',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
