# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-26 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181227_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='User_latitude_Coordinates',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='User_longtitude_Coordinates',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
